stages:
  - test

.test_template: &test_definition
  stage: test
  image: python:3.8
  before_script:
  - pip install pipenv
  - pipenv install --system --dev
  except:
  - tags

qualities:
  <<: *test_definition
  script:
  - black --check . 
  - flake8 .
  - mypy --config-file ./setup.cfg .
